we must add CreateChatInviteLink and some assistants and change name one method
Ali-Toosi/django-tgbot pull request #20
Opened 2023-07-12 14:04 UTC by ABOLFAZLVALIKHANI

I added the CreateChatInviteLink method. For this, I added the assistants folder to the project.
We can use assistants later , for example:

    Better access to return values ​​from the Telegram side
    Adding some general functionality, for example checking a user's membership

Assistants can be used in various ways. I will try to add more general features to this section in due course

change name method kickChatMember to banChatMember
I kept the previous name so that users don't have problems when changing the version

2023-07-13 14:53 UTC, Ali-Toosi commented
Thanks, I'll review this tomorrow.

2023-07-13 19:27 UTC, ABOLFAZLVALIKHANI commented
you're welcome

2023-07-13 19:27 UTC, ABOLFAZLVALIKHANI commented
you're welcome

2023-07-14 11:51 UTC, Ali-Toosi requested changes

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/bot_api_user.py
> +
```suggestion
```

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/bot_api_user.py
> +
```suggestion
```

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/bot_api_user.py
> +
```suggestion
```

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/bot_api_user.py
> +        return self.request_and_result(create_params_from_args(locals()), CreateChatInviteLink )
```suggestion
    
    def createChatInviteLink(self, chat_id, name : str = None, expire_date : int = None, member_limit : int = 5, 
                            creates_join_request : bool  = False) :
        return self.request_and_result(create_params_from_args(locals()), CreateChatInviteLink)
```

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/bot_api_user.py
> +        return self.request_and_result(create_params_from_args(locals()), CreateChatInviteLink )
In addition to removing the spaces as above, please also make sure the parameters are exactly like they are defined in Telegram API. In their API, there is no default value for `member_limit` or `creates_join_request`.

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/assistants/createChatInviteLink.py
> +import inspect
Not used, can be deleted.

```suggestion
```

2023-07-14 11:51 UTC, Ali-Toosi commented on django_tgbot/assistants/createChatInviteLink.py
I understand you want to use this as the type for a `ChatInviteLink`. However, there already is a folder for all the types. Please move this to `django_tgbot/types/chatinvitelink.py` and make sure its style is the same as other types in that folder (should inherit the same class, the class name should be exactly like Telegram `ChatInviteLink`,  etc.).

2023-07-15 06:49 UTC, ABOLFAZLVALIKHANI commented on django_tgbot/assistants/createChatInviteLink.py
`ChatInviteLink` is not a TYPE [(!)](https://core.telegram.org/bots/api#createchatinvitelink), Therefore, I suggest not to put it in the type folder.
I already tried to take this as Type. But it was not ideal and I encountered some problems.
so we can't  make sure its style is the same as other types!

2023-07-15 09:10 UTC, Ali-Toosi commented on django_tgbot/assistants/createChatInviteLink.py
It is a type: https://core.telegram.org/bots/api#chatinvitelink
You are referring to the method. But there is also a type. That method basically creates one ChatInviteLink object.

2023-07-25 02:05 UTC, Ali-Toosi commented on django_tgbot/assistants/createChatInviteLink.py
I'm closing the PR. Feel free to re-open it if you wanted to make changes.

2023-07-25 02:05 UTC, closed without merging